# Generated by Django 3.1.7 on 2021-06-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.TextField()),
                ('name', models.TextField()),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'django_command_disable',
                'ordering': ('app', 'name'),
            },
        ),
        migrations.AddIndex(
            model_name='config',
            index=models.Index(fields=['app'], name='django_comm_app_4f7ac8_idx'),
        ),
        migrations.AddIndex(
            model_name='config',
            index=models.Index(fields=['name'], name='django_comm_name_b1047f_idx'),
        ),
        migrations.AddIndex(
            model_name='config',
            index=models.Index(fields=['is_enabled'], name='django_comm_is_enab_1cfeb4_idx'),
        ),
    ]
